# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-28 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_business_rules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessrulemodel',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='businessrulemodel',
            name='name',
            field=models.TextField(unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='businessrulemodel',
            name='rules',
            field=models.TextField(default={}, verbose_name='rules'),
        ),
    ]
